
project_id = "yvvqfcwhskthbbjspcvi"

[functions.gumroad-migration]
verify_jwt = false

[functions.product-migration-agent]
verify_jwt = false

[functions.product-preview-generator]
verify_jwt = false
