
project_id = "yvvqfcwhskthbbjspcvi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.gumroad-migration]
verify_jwt = false

[functions.product-migration-agent]
verify_jwt = false

[functions.product-preview-generator]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.browser-automation]
verify_jwt = false

[functions.n8n-payhip-automation]
verify_jwt = false

[functions.migration-callback]
verify_jwt = false

[edge_runtime]
enabled = true
port = 54329

[analytics]
enabled = false
port = 54327
vector_port = 54328
